---
version: '3'

services:
  image-request-handler:
    image: image-request-handler:latest
    build:
      context: lambdas/image_request_handler
      dockerfile: Dockerfile
    ports:
      - 9010:8080
    depends_on:
      localstack-request-handler:
        condition: service_healthy
      image-processor:
        condition: service_started
      mock-sirius-web:
        condition: service_started
    volumes:
      - ./lambdas/.aws-lambda-rie:/aws-lambda
      - ./lambdas/image_request_handler/app:/function/app
    environment:
      AWS_ACCESS_KEY_ID: FAKE
      AWS_SECRET_ACCESS_KEY: FAKE
      ENVIRONMENT: local
      VERSION: v1
      LOGGER_LEVEL: DEBUG
    entrypoint: /aws-lambda/aws-lambda-rie /usr/local/bin/python -m awslambdaric app.handler.lambda_handler

  image-processor:
    image: image-processor:latest
    build:
      context: lambdas/image_processor
      dockerfile: Dockerfile
    ports:
      - 9011:8080
    depends_on:
      localstack-processor:
        condition: service_healthy
    volumes:
      - ./lambdas/.aws-lambda-rie:/aws-lambda
      - ./lambdas/image_processor/app:/function/app
      - ./lambdas/image_processor/extraction:/function/extraction
      - ./tmp_images:/tmp
    environment:
      AWS_ACCESS_KEY_ID: FAKE
      AWS_SECRET_ACCESS_KEY: FAKE
      ENVIRONMENT: local
      TARGET_ENVIRONMENT: local
      SECRET_PREFIX: local
      SIRIUS_URL: http://mock-sirius-web:80
      SIRIUS_URL_PART: /v1
      SESSION_DATA: publicapi@opgtest.com
      AWS_LAMBDA_FUNCTION_TIMEOUT: 900
      LOGGER_LEVEL: DEBUG

    entrypoint: /aws-lambda/aws-lambda-rie /usr/local/bin/python -m awslambdaric app.handler.lambda_handler

  unit-tests-request-handler:
    image: unit-tests-request-handler:latest
    build:
      context: lambdas/image_request_handler
      dockerfile: Dockerfile-tests
    volumes:
      - ./lambdas/image_request_handler/app:/lambdas/image_request_handler/app
      - ./lambdas/image_request_handler/tests:/lambdas/image_request_handler/tests
    environment:
      AWS_ACCESS_KEY_ID: FAKE
      AWS_SECRET_ACCESS_KEY: FAKE
      ENVIRONMENT: local

  unit-tests-processor:
    image: unit-tests-processor:latest
    build:
      context: lambdas/image_processor
      dockerfile: Dockerfile-tests
    volumes:
      - ./lambdas/image_processor/app:/function/app
      - ./lambdas/image_processor/tests:/function/tests
    environment:
      AWS_ACCESS_KEY_ID: FAKE
      AWS_SECRET_ACCESS_KEY: FAKE
      ENVIRONMENT: local

  localstack-request-handler:
    image: localstack-request-handler:latest
    build:
      context: ./local-services/localstack-request-handler
      dockerfile: Dockerfile
    environment:
      SERVICES: s3,lambda,apigateway
      DEFAULT_REGION: eu-west-1
      USE_SINGLE_REGION: 1
      DEBUG: 1
      HOSTNAME_EXTERNAL: localstack-request-handler
      LAMBDA_EXECUTOR: docker
      LAMBDA_REMOVE_CONTAINERS: "true"
      LAMBDA_FORWARD_URL: http://image-request-handler:8080
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - ./docs/openapi/image-request-handler.yml:/tmp/image-request-handler.yml
    ports:
      - 4566:4566
    healthcheck:
      test: ["CMD", "curl", "http://localhost:4566/health?reload"]

  localstack-processor:
    image: localstack-processor:latest
    build:
      context: ./local-services/localstack-processor
      dockerfile: Dockerfile
    environment:
      SERVICES: secretsmanager,lambda,sqs
      DEFAULT_REGION: eu-west-1
      USE_SINGLE_REGION: 1
      DEBUG: 1
      HOSTNAME_EXTERNAL: localstack-processor
      LAMBDA_EXECUTOR: docker
      LAMBDA_REMOVE_CONTAINERS: "true"
      LAMBDA_FORWARD_URL: http://image-processor:8080
      DOCKER_HOST: unix:///var/run/docker.sock
    ports:
      - 4567:4566
    healthcheck:
      test: ["CMD", "curl", "http://localhost:4566/health?reload"]

#Mock Sirius LB
  mock-sirius-web:
    build:
      context: ./mock-services/sirius/web
      dockerfile: Dockerfile
    image: mock-sirius-web:latest
    container_name: api-gateway
    depends_on:
      - mock-sirius
    volumes:
      - ./mock-services/sirius/web/nginx-local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7012:80

  mock-sirius:
    build:
      context: ./mock-services/sirius/app
      dockerfile: Dockerfile
    image: mock-sirius:latest
    volumes:
      - ./mock-services/sirius/app/sirius-local.yml:/app/sirius.yml:ro
    ports:
      - 7013:4010
