---
version: '3'

services:
  image-request-handler:
    build:
      context: ./lambda/image-request-handler
      dockerfile: Dockerfile
    ports:
      - "9010:8080"
    depends_on:
      - localstack
    volumes:
      - ./lambda/.aws-lambda-rie:/aws-lambda
      - ./lambda/image-request-handler/app:/function/app
    entrypoint: /aws-lambda/aws-lambda-rie /usr/local/bin/python -m awslambdaric app.handler.lambda_handler

  localstack:
    build:
      context: ./local-services/localstack
      dockerfile: Dockerfile
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      - SERVICES=sqs,secretsmanager,s3,lambda
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-1
      - USE_SINGLE_REGION=1
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS="true"
      - LAMBDA_FORWARD_URL=http://image-request-handler:8080

# Mock API gateway and image request handler
# This will largely be replaced as we move forward and moved into use an LPA repo as it's mock.
# Useful here for the time being.
  api-gateway:
    container_name: api-gateway
    image: nginx:stable-alpine
    depends_on:
      - mock-image-request-handler
    command: 'nginx -g "daemon off;"'
    volumes:
      - ./mock-services/image-request-handler/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7010:5000

  mock-image-request-handler:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/image-request-handler.yml'
    volumes:
      - ./docs/openapi/image-request-handler.yml:/tmp/image-request-handler.yml:ro
    ports:
      - 7011:4010
