ARG FUNCTION_DIR="/function"

# === BUILD IMAGE ===
FROM python:3.12-slim@sha256:eb6e98dff53cf7c7be93381e05c94409be7214bdf30f5265bae1d3f5c5b3eb8c AS builder
# Include global arg in this stage of the build
ARG FUNCTION_DIR
# Set the working directory to /app
WORKDIR ${FUNCTION_DIR}
# Copy the requirements file to the working directory
COPY requirements.txt requirements.txt
COPY requirements-tests.txt requirements-tests.txt
# Install tesseract build dependencies
RUN apt-get update && \
    apt-get upgrade expat -y && \
    apt-get install -y libtesseract-dev libleptonica-dev tesseract-ocr build-essential && \
    rm -rf /var/lib/apt/lists/*
# Pip dependency installs
RUN python -m pip install --upgrade pip
RUN python -m pip install \
        --target ${FUNCTION_DIR} \
        --requirement requirements.txt
RUN python -m pip install \
        --target ${FUNCTION_DIR} \
        --requirement requirements-tests.txt
COPY app ${FUNCTION_DIR}/app
COPY tests ${FUNCTION_DIR}/tests
COPY extraction ${FUNCTION_DIR}/extraction


# === FINAL IMAGE ===
FROM python:3.12-slim@sha256:eb6e98dff53cf7c7be93381e05c94409be7214bdf30f5265bae1d3f5c5b3eb8c
# Include global arg in this stage of the build
ARG FUNCTION_DIR
# Set the working directory to /app
WORKDIR ${FUNCTION_DIR}
# Install runtime dependencies
RUN apt-get update && \
    apt-get upgrade expat -y && \
    apt-get install -y libgl1 libglx-mesa0 libglib2.0-0 poppler-utils libtesseract-dev libleptonica-dev tesseract-ocr libzbar0 libzbar-dev && \
    rm -rf /var/lib/apt/lists/*
# Copy only the installed packages from the previous stage to the working directory
COPY --from=builder ${FUNCTION_DIR} ${FUNCTION_DIR}
COPY run-tests.sh run-tests.sh
RUN pip3 install coverage==7.2.5 && chmod 755 run-tests.sh
# Set the entrypoint for the unit tests
ENTRYPOINT [ "/function/run-tests.sh" ]
