name: "[Workflow] Cleanup PR Workspaces"

on:
  schedule:
    # 4am every day except Sundays
    - cron: '0 4 * * 0-6'

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  terraform_environment_cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8eb1f6a495037164bea451156472f35fdd6bafc0
      - uses: unfor19/install-aws-cli-action@27d6061dae5d39e89be4d2246824f15e111a7e06
      - uses: hashicorp/setup-terraform@b033326c2c3fb4bfd7e831ad17ba17756aece0f3
        with:
          terraform_version: 1.3.7
          terraform_wrapper: false

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@3bd0e770227859bbc3298e52dc2bf4fc0d3300ae
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: eu-west-1
          role-duration-seconds: 3600
          role-session-name: OPGUalIapClearupEnvs

      - name: Install Terraform Workspace Manager
        run: |
          wget https://github.com/TomTucka/terraform-workspace-manager/releases/download/v0.3.1/terraform-workspace-manager_Linux_x86_64.tar.gz -O $HOME/terraform-workspace-manager.tar.gz
          sudo tar -xvf $HOME/terraform-workspace-manager.tar.gz -C /usr/local/bin
          sudo chmod +x /usr/local/bin/terraform-workspace-manager

      - name: Terraform Init
        working-directory: terraform/environment
        run: terraform init -input=false

      - name: Destroy PR Terraform Workspaces
        working-directory: terraform/environment
        env:
          TF_VAR_pagerduty_token: ${{ secrets.PAGERDUTY_TOKEN }}
        run: |
          ./scripts/workspace_cleanup.sh $(terraform-workspace-manager -protected-workspaces=true -aws-account-id=288342028542 -aws-iam-role=integrations-ci)
