on:
  workflow_call:
    inputs:
      terraform_path:
        description: 'The name of the terraform paths'
        required: true
        type: string
      workspace:
        description: 'Terraform workspace'
        required: true
        type: string
      image_tag:
        description: 'Image tag to use'
        required: false
        type: string
      mock_sirius:
        description: 'Mock sirius'
        default: 'false'
        required: false
        type: string
    secrets:
      aws_access_key_id_actions:
        required: true
      aws_secret_access_key_actions:
        required: true
      pagerduty_token:
        required: false

jobs:
  terraform_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install AWS Cli
        uses: unfor19/install-aws-cli-action@27d6061dae5d39e89be4d2246824f15e111a7e06

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@a75f1a3ccea3c602b976c7c8c15b0c200cf101d0
        with:
          terraform_version: 1.3.7

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@587276aa2b7ab3e81491bc89886f7805ee29494c
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id_actions }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key_actions }}
          aws-region: eu-west-1
          role-duration-seconds: 3600
          role-session-name: OPGUALIaPGithubAction

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ./${{ inputs.terraform_path }}

      - name: Terraform Plan
        env:
          TF_WORKSPACE: ${{ inputs.workspace }}
          TF_VAR_image_tag: ${{ inputs.image_tag }}
          TF_VAR_use_mock_sirius: ${{ inputs.mock_sirius }}
          TF_VAR_pagerduty_token: ${{ secrets.pagerduty_token }}
        run: |
          terraform workspace show
          terraform plan -input=false -parallelism=30
        working-directory: ./${{ inputs.terraform_path }}

      - name: Terraform Apply
        env:
          TF_WORKSPACE: ${{ inputs.workspace }}
          TF_VAR_image_tag: ${{ inputs.image_tag }}
          TF_VAR_use_mock_sirius: ${{ inputs.mock_sirius }}
          TF_VAR_pagerduty_token: ${{ secrets.pagerduty_token }}
        run: terraform apply -lock-timeout=300s -input=false -auto-approve -parallelism=30
        working-directory: ./${{ inputs.terraform_path }}
