name: "Destroy Environment"

on:
  workflow_call:
    inputs:
      workspace_name:
        description: "The terraform workspace to target for environment actions"
        required: true
        type: string
      terraform_path:
        description: 'The name of the terraform paths'
        required: true
        type: string
      oidc_role:
        description: 'The OIDC role to assume for AWS access'
        required: true
        type: string
      default_role:
        description: 'The default CI role to assume'
        required: true
        type: string
      management_role:
        description: 'The management CI role to assume'
        required: true
        type: string
    secrets:
      ssh_private_key:
        description: "SSH Deploy Key"
        required: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Error if protected
        if: ${{ contains(fromJSON('["development", "preproduction", "production", "demo", "integration"]'), inputs.workspace_name) }}
        run: |
          echo "Cannot destroy protected Environment"
          exit 1

  terraform_environment_workflow:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: check
    env:
      TF_VAR_default_role: ${{ inputs.default_role }}
      TF_VAR_management_role: ${{ inputs.management_role }}
      TF_VAR_image_tag: "latest"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: '0'

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.13.1
          terraform_wrapper: false

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_role }}
          role-duration-seconds: 3600
          role-session-name: OPGLPACodesDestroyEnvGithubAction

      - id: deploy-key
        uses: ministryofjustice/opg-github-actions/actions/github-deploy-key@77bb12e7fec3bcee9a6a35cb21361195e027a12a # v4.9.0
        with:
          deploy_key: ${{ secrets.ssh_private_key }}

      - name: Terraform Init
        working-directory: ./${{ inputs.terraform_path }}
        env:
          TF_WORKSPACE: default

        run: terraform init -input=false -upgrade

      - name: Terraform Destroy
        working-directory: ./${{ inputs.terraform_path }}
        env:
          WORKSPACE_NAME: ${{ inputs.workspace_name }}
        run: |
          terraform workspace select $WORKSPACE_NAME
          terraform destroy -auto-approve
          terraform workspace select default
          terraform workspace delete $WORKSPACE_NAME
