on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
        type: string
      workspace:
        description: 'Workspace to use'
        required: true
        type: string

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: '0'

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_DEVELOPMENT_TEST_RUNNER_ROLE }}
          role-duration-seconds: 3600
          role-session-name: OPGUALIaPIntegrationTestsGithubAction

      - name: Run integration tests
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          WORKSPACE: ${{ inputs.workspace }}
        run: docker compose run --rm --build integration-test
