on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
        type: string
      workspace:
        description: 'Workspace to use'
        required: true
        type: string

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: '0'

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_DEVELOPMENT_TEST_RUNNER_ROLE }}
          role-duration-seconds: 3600
          role-session-name: OPGUALIaPIntegrationTestsGithubAction

      - name: Run integration tests
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          WORKSPACE: ${{ inputs.workspace }}
        run: docker compose run --rm --build integration-test
