on:
  workflow_call:
    inputs:
      apply:
        description: 'Whether to apply the terraform or just plan'
        default: false
        required: true
        type: boolean
      default_role:
        description: 'The default CI role to assume'
        required: true
        type: string
      image_tag:
        description: 'Image tag to use'
        required: false
        type: string
      management_role:
        description: 'The management CI role to assume'
        required: false
        type: string
      mock_sirius:
        description: 'Mock sirius'
        default: 'false'
        required: false
        type: string
      oidc_role:
        description: 'The OIDC role to assume for AWS access'
        required: true
        type: string
      terraform_path:
        description: 'The name of the terraform paths'
        required: true
        type: string
      use_ssh_private_key:
        type: boolean
        description: "Flag used to decide if the workflow should use the SSH_PRIVATE_KEY secret"
        required: false
        default: false
      workspace:
        description: 'Terraform workspace'
        required: true
        type: string
    secrets:
      pagerduty_token:
        required: false
      ssh_private_key:
        required: false

jobs:
  terraform_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '0'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.13.1

      - name: Setup SSH private key
        id: deploy-key
        if: inputs.use_ssh_private_key == true #pragma: allowlist secret
        uses: ministryofjustice/opg-github-actions/actions/github-deploy-key@ceeda9d30ec7f6705c819d0b7664b9a79df99a3b # v4.8.0
        with:
          deploy_key: ${{ secrets.ssh_private_key }}

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_role }}
          role-duration-seconds: 3600
          role-session-name: OPGUALIaPGithubAction

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ./${{ inputs.terraform_path }}

      - name: Terraform Plan
        working-directory: ./${{ inputs.terraform_path }}
        env:
          TF_WORKSPACE: ${{ inputs.workspace }}
          TF_VAR_default_role: ${{ inputs.default_role }}
          TF_VAR_management_role: ${{ inputs.management_role }}
          TF_VAR_image_tag: ${{ inputs.image_tag }}
          TF_VAR_use_mock_sirius: ${{ inputs.mock_sirius }}
          TF_VAR_pagerduty_token: ${{ secrets.pagerduty_token }}
        run: |
          terraform workspace show
          terraform plan -lock-timeout=300s -input=false -parallelism=30 -out=${{ env.TF_WORKSPACE }}.plan

      - name: Terraform Apply
        working-directory: ./${{ inputs.terraform_path }}
        if: inputs.apply == true
        env:
          TF_WORKSPACE: ${{ inputs.workspace }}
          TF_VAR_default_role: ${{ inputs.default_role }}
          TF_VAR_management_role: ${{ inputs.management_role }}
          TF_VAR_image_tag: ${{ inputs.image_tag }}
          TF_VAR_use_mock_sirius: ${{ inputs.mock_sirius }}
          TF_VAR_pagerduty_token: ${{ secrets.pagerduty_token }}
        run: terraform apply -lock-timeout=300s -input=false -auto-approve -parallelism=30 ${{ env.TF_WORKSPACE }}.plan
