permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag for docker image"
        required: true
        type: string
      branch_name:
        description: "Branch we are on"
        required: true
        type: string
    secrets:
      SNYK_OPG_ORG_TOKEN:
        required: true

jobs:
  docker_build_scan_push:
    name: Build, Scan and Push Lambdas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "lpa-iap-request-handler-lambda"
            path: "lambdas/image_request_handler"
            snyk_policy_path: "lambdas/image_request_handler/.snyk"
          - name: "lpa-iap-scan-processor-lambda"
            path: "lambdas/image_processor"
            snyk_policy_path: "lambdas/image_processor/.snyk"
          - name: "lpa-iap-mock-sirius"
            path: "mock-services/sirius/app"
            snyk_policy_path: "mock-services/sirius/app/.snyk"
          - name: "lpa-iap-mock-sirius-web"
            path: "mock-services/sirius/web"
            snyk_policy_path: "mock-services/sirius/web/.snyk"
    steps:
      - name: Check out code
        id: checkout_code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build Container
        id: build_container
        run: docker build --platform linux/amd64 --provenance=false --file ${{ matrix.path }}/Dockerfile --tag ${{ matrix.name }}:latest ${{ matrix.path }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_MANAGEMENT_ECR_ROLE }}
          role-duration-seconds: 900
          role-session-name: OPGLPAIaPECRPushGithubAction

      - name: ecr login
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@f2e9fc6c2b355c1890b65e6f6f0e2ac3e6e22f78 # v2.1.2
        with:
          registries: 311462405659

      - name: Snyk Scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@ceeda9d30ec7f6705c819d0b7664b9a79df99a3b # v4.8.0
        with:
          SNYK_TEST_IMAGE: ${{ matrix.name }}:latest
          SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
          snyk_test_args: >
            --severity-threshold=high --fail-on=upgradable
          snyk_policy_path: ./${{ matrix.snyk_policy_path }}

      - name: Upload Snyk scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
        if: always()
        with:
          sarif_file: "test-results/snyk.sarif"

      - name: Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          ECR_REPOSITORY: integrations/${{ matrix.name }}
          BRANCH_NAME: ${{ inputs.branch_name }}
        run: |
          docker tag ${{ matrix.name }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.tag }}
          if [ $BRANCH_NAME == "main" ]; then
            docker tag ${{ matrix.name }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker tag ${{ matrix.name }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:main-${{ inputs.tag }}
          fi
            echo "skipping push for now..."
            docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
