on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
        type: string
      workspace:
        description: 'Workspace to use'
        required: true
        type: string

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: '0'

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_DEVELOPMENT_TEST_RUNNER_ROLE }}
          role-duration-seconds: 3600
          role-session-name: OPGUALIaPIntegrationTestsGithubAction

      - name: Run integration tests
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          WORKSPACE: ${{ inputs.workspace }}
        run: docker compose run --rm --build integration-test
