name: "[Terraform] Validate terraform"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      oidc_role:
        description: 'The OIDC role to assume for AWS access'
        required: true
        type: string
      workspace:
        description: 'Terraform workspace'
        required: true
        type: string
    secrets:
      ssh_private_key:
        required: false
      source_github_token:
        required: true
jobs:
  lint-terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - folder: 'environment'
          - folder: 'account'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: terraform_version
        name: Get terraform version
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@ceeda9d30ec7f6705c819d0b7664b9a79df99a3b # v4.8.0
        with:
          terraform_directory: "./terraform/${{ matrix.folder }}"

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ steps.terraform_version.outputs.version }}

      - uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
        name: Setup TFLint

      - name: configure AWS credentials for terraform
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_role }}
          role-duration-seconds: 1800
          role-session-name: OPGLPAIaPTerraformLintGithubAction

      - name: terraform fmt ${{ matrix.folder }} check
        run: terraform fmt --check --recursive
        working-directory: ./terraform/${{ matrix.folder }}

      - name: terraform lint ${{ matrix.folder }}
        run:  tflint --recursive
        working-directory: ./terraform/${{ matrix.folder }}

      - name: Setup SSH private key
        id: deploy-key
        uses: ministryofjustice/opg-github-actions/actions/github-deploy-key@ceeda9d30ec7f6705c819d0b7664b9a79df99a3b # v4.8.0
        with:
          deploy_key: ${{ secrets.ssh_private_key }}

      - name: terraform validate ${{ inputs.workspace }}
        env:
          TF_WORKSPACE: default
        run: |
          terraform --version
          terraform init
          echo $TF_WORKSPACE
          terraform validate
        working-directory: ./terraform/${{ matrix.folder }}
