permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag for docker image"
        required: true
        type: string
      branch_name:
        description: "Branch we are on"
        required: true
        type: string
    secrets:
      SNYK_OPG_ORG_TOKEN:
        required: true

jobs:
  docker_build_scan_push:
    name: Build, Scan and Push Lambdas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "lpa-iap-request-handler-lambda"
            path: "lambdas/image_request_handler"
            snyk_policy_path: "lambdas/image_request_handler/.snyk"
          - name: "lpa-iap-scan-processor-lambda"
            path: "lambdas/image_processor"
            snyk_policy_path: "lambdas/image_processor/.snyk"
          - name: "lpa-iap-mock-sirius"
            path: "mock-services/sirius/app"
            snyk_policy_path: "mock-services/sirius/app/.snyk"
          - name: "lpa-iap-mock-sirius-web"
            path: "mock-services/sirius/web"
            snyk_policy_path: "mock-services/sirius/web/.snyk"
    steps:
      - name: Check out code
        id: checkout_code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Build Container
        id: build_container
        run: docker build --platform linux/amd64 --provenance=false --file ${{ matrix.path }}/Dockerfile --tag ${{ matrix.name }}:latest ${{ matrix.path }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_MANAGEMENT_ECR_ROLE }}
          role-duration-seconds: 900
          role-session-name: OPGLPAIaPECRPushGithubAction

      - name: ecr login
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@fa648b43de3d4d023bcb3f89ed6940096949c419 # v2.1.5
        with:
          registries: 311462405659

      - name: Snyk Scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@77bb12e7fec3bcee9a6a35cb21361195e027a12a # v4.9.0
        with:
          SNYK_TEST_IMAGE: ${{ matrix.name }}:latest
          SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
          snyk_test_args: >
            --severity-threshold=high --fail-on=upgradable
          snyk_policy_path: ./${{ matrix.snyk_policy_path }}

      - name: Upload Snyk scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        if: always()
        with:
          sarif_file: "test-results/snyk.sarif"

      - name: Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          ECR_REPOSITORY: integrations/${{ matrix.name }}
          BRANCH_NAME: ${{ inputs.branch_name }}
        run: |
          docker tag ${{ matrix.name }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.tag }}
          if [ $BRANCH_NAME == "main" ]; then
            docker tag ${{ matrix.name }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker tag ${{ matrix.name }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:main-${{ inputs.tag }}
          fi
            echo "skipping push for now..."
            docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
