name: "[Workflow] Path to Live"

on:
  push:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  terraform_environment_plan_apply:
    name: Terraform Plan and Apply Account
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      terraform_path: 'terraform/account'
      image_tag: ${{ needs.create_tags.outputs.version_tag }}
      workspace: development
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  workflow_complete:
    name: Workflow Complete
    needs: ['terraform_environment_plan_apply']
    runs-on: ubuntu-latest
    steps:
      - name: Completion message
        run: echo "Workflow Complete - No path to live yet"
