name: PR Closed Workflow

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Extract branch name
    outputs:
      raw_branch: ${{ steps.extract_branch.outputs.branch_raw }}
      formatted_branch: ${{ steps.extract_branch.outputs.branch_formatted }}
    steps:
      - name: Extract branch
        shell: bash
        run: |
          echo "branch_raw=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF##*/}})" >> $GITHUB_OUTPUT
          echo "branch_formatted=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF##*/}} | tr -cd '[:alnum:]' | tr '[:upper:]' '[:lower:]' | cut -c1-8)" >> $GITHUB_OUTPUT
        id: extract_branch

  destroy-pr-env:
    name: Destroy PR Environment
    needs: [branch_name]
    uses: ./.github/workflows/sub-task-destroy-environment.yml
    with:
      workspace_name: ${{ github.event.pull_request.number }}${{ needs.branch_name.outputs.formatted_branch }}
      terraform_path: "terraform/environment"
      default_role: ${{ vars.DEVELOPMENT_ROLE }}
      oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
    secrets:
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}
