name: "[Workflow] Pull Request Path"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: write
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  pr_label:
    runs-on: ubuntu-latest
    name: Label PR
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          configuration-path: ".github/labeller.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  branch_name:
    runs-on: ubuntu-latest
    name: Extract branch name
    outputs:
      raw_branch: ${{ steps.extract_branch.outputs.branch_raw }}
      formatted_branch: ${{ steps.extract_branch.outputs.branch_formatted }}
    steps:
      - name: Extract branch
        shell: bash
        run: |
          echo "branch_raw=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF##*/}})" >> $GITHUB_OUTPUT
          echo "branch_formatted=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF##*/}} | tr -cd '[:alnum:]' | tr '[:upper:]' '[:lower:]' | cut -c1-8)" >> $GITHUB_OUTPUT
        id: extract_branch

  create_tags:
    name: Create Tags
    needs: ['branch_name']
    uses: ./.github/workflows/sub-task-tags.yml
    with:
      branch_name: ${{ needs.branch_name.outputs.formatted_branch }}
    secrets:
      source_github_token: ${{ secrets.GITHUB_TOKEN }}

  terraform_lint:
    name: lint terraform code
    uses: ./.github/workflows/sub-task-lint.yml
    needs: ['branch_name']
    with:
      oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
      workspace: ${{ needs.branch_name.outputs.formatted_branch }}
    secrets:
      source_github_token: ${{ secrets.GITHUB_TOKEN }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  unit_tests:
    name: Unit tests
    needs: ['create_tags', 'branch_name']
    uses: ./.github/workflows/sub-task-unit-tests.yml

  form_tools_tests:
    name: Form tools tests
    needs: ['create_tags', 'branch_name']
    uses: ./.github/workflows/sub-task-form-tools-tests.yml

  docker_build_scan_push:
    name: Build, Scan and Push
    needs: ['create_tags', 'branch_name']
    uses: ./.github/workflows/sub-task-docker-build.yml
    with:
      tag: ${{ needs.create_tags.outputs.version_tag }}
      branch_name: ${{ needs.branch_name.outputs.formatted_branch }}
    secrets:
      SNYK_OPG_ORG_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}

  terraform_apply_ephemeral_environment_with_mock_sirius:
    name: Terraform Plan and Apply Environment
    needs: [
      'docker_build_scan_push',
      'terraform_lint',
      'create_tags',
      'branch_name',
      'unit_tests',
      'form_tools_tests',
    ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      apply: true
      default_role: ${{ vars.DEVELOPMENT_ROLE }}
      image_tag: ${{ needs.create_tags.outputs.version_tag }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
      mock_sirius: "true"
      oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
      terraform_path: 'terraform/environment'
      use_ssh_private_key: true
      workspace: ${{ needs.branch_name.outputs.formatted_branch }}
    secrets:
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  plan_path_to_live:
    strategy:
      matrix:
        include:
          - workspace: development
            terraform_path: "terraform/account"
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.DEVELOPMENT_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
            use_ssh_private_key: false
          - workspace: development
            terraform_path: "terraform/environment"
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.DEVELOPMENT_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
            use_ssh_private_key: true
          - workspace: preproduction
            terraform_path: "terraform/account"
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.PREPRODUCTION_PULL_REQUEST_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
            use_ssh_private_key: false
          - workspace: preproduction
            terraform_path: "terraform/environment"
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.PREPRODUCTION_PULL_REQUEST_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
            use_ssh_private_key: true
          - workspace: production
            terraform_path: "terraform/account"
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.PRODUCTION_PULL_REQUEST_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
            use_ssh_private_key: false
          - workspace: production
            terraform_path: "terraform/environment"
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.PRODUCTION_PULL_REQUEST_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
            use_ssh_private_key: true
    name: "TF Plan: ${{matrix.terraform_path}} - ${{ matrix.workspace }}"
    needs: [
      'docker_build_scan_push',
      'terraform_lint',
      'create_tags',
      'branch_name',
      'unit_tests',
      'form_tools_tests',
    ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      apply: false
      default_role: ${{ matrix.default_role }}
      image_tag: ${{ needs.create_tags.outputs.version_tag }}
      management_role: ${{ matrix.management_role }}
      oidc_role: ${{ matrix.oidc_role }}
      terraform_path: ${{ matrix.terraform_path }}
      use_ssh_private_key: ${{ matrix.use_ssh_private_key }}
      workspace: ${{ matrix.workspace }}
    secrets:
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  integration_tests:
    name: Run integration tests
    needs: [
      'branch_name',
      'create_tags',
      'plan_path_to_live',
      'terraform_apply_ephemeral_environment_with_mock_sirius'
    ]
    uses: ./.github/workflows/sub-task-integration-tests.yml
    with:
      environment: 'development'
      workspace: ${{ needs.branch_name.outputs.formatted_branch }}

  terraform_apply_ephemeral_environment:
    name: Terraform Plan and Apply Environment
    needs: [
      'integration_tests',
      'create_tags',
      'branch_name'
    ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      apply: true
      default_role: ${{ vars.DEVELOPMENT_ROLE }}
      image_tag: ${{ needs.create_tags.outputs.version_tag }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
      oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
      terraform_path: 'terraform/environment'
      use_ssh_private_key: true
      workspace: ${{ needs.branch_name.outputs.formatted_branch }}
    secrets:
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  workflow_complete:
    name: Workflow Complete
    runs-on: ubuntu-latest
    needs: ['terraform_apply_ephemeral_environment']
    steps:
      - name: Completion message
        run: echo "Workflow Complete"
