name: "[Workflow] Path to Live"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Extract branch name
    outputs:
      raw_branch: ${{ steps.extract_branch.outputs.branch_raw }}
      formatted_branch: ${{ steps.extract_branch.outputs.branch_formatted }}
    steps:
      - name: extract branch
        shell: bash
        run: |
          echo "branch_raw=main" >> $GITHUB_OUTPUT
          echo "branch_formatted=main" >> $GITHUB_OUTPUT
        id: extract_branch

  create_tags:
    name: Create Tags
    needs: ['branch_name']
    uses: ./.github/workflows/sub-task-tags.yml
    with:
      branch_name: ${{ needs.branch_name.outputs.formatted_branch }}
    secrets:
      source_github_token: ${{ secrets.GITHUB_TOKEN }}

  docker_build_scan_push:
    name: Build, Scan and Push
    needs: [ 'create_tags', 'branch_name' ]
    uses: ./.github/workflows/sub-task-docker-build.yml
    with:
      tag: ${{ needs.create_tags.outputs.version_tag }}
      branch_name: ${{ needs.branch_name.outputs.formatted_branch }}
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  development_account_plan_apply:
    name: Development Account Terraform Plan and Apply
    needs: [
      'docker_build_scan_push',
      'create_tags'
    ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      terraform_path: 'terraform/account'
      image_tag: ${{ needs.create_tags.outputs.version_tag }}
      workspace: development
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      pagerduty_token: ${{ secrets.PAGERDUTY_TOKEN }}

  development_environment_apply_with_mock_sirius:
    name: Development Environment Terraform Plan and Apply Mock Sirius
    needs: [
      'development_account_plan_apply',
      'create_tags'
    ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      terraform_path: 'terraform/environment'
      image_tag: ${{ needs.create_tags.outputs.version_tag }}
      mock_sirius: "true"
      use_ssh_private_key: true
      workspace: development
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  development_integration_tests:
    name: Development Run integration tests
    needs: [
      'development_environment_apply_with_mock_sirius'
    ]
    uses: ./.github/workflows/sub-task-integration-tests.yml
    with:
      environment: 'development'
      workspace: 'development'
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  development_environment_plan_apply:
    name: Development Environment Terraform Plan and Apply
    needs: [
      'development_integration_tests',
      'create_tags'
    ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      terraform_path: 'terraform/environment'
      image_tag: ${{ needs.create_tags.outputs.version_tag }}
      use_ssh_private_key: true
      workspace: development
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  preproduction_account_plan_apply:
    name: Preproduction Account Terraform Plan and Apply
    needs: [
      'development_environment_plan_apply',
      'create_tags'
    ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      terraform_path: 'terraform/account'
      image_tag: main-${{ needs.create_tags.outputs.version_tag }}
      workspace: preproduction
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      pagerduty_token: ${{ secrets.PAGERDUTY_TOKEN }}

  preproduction_environment_plan_apply:
    name: Preproduction Environment Terraform Plan and Apply
    needs: [
      'preproduction_account_plan_apply',
      'create_tags'
    ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      terraform_path: 'terraform/environment'
      image_tag: main-${{ needs.create_tags.outputs.version_tag }}
      use_ssh_private_key: true
      workspace: preproduction
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  production_account_plan_apply:
    name: Production Account Terraform Plan and Apply
    needs: [
      'preproduction_environment_plan_apply',
      'create_tags'
    ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      terraform_path: 'terraform/account'
      image_tag: main-${{ needs.create_tags.outputs.version_tag }}
      workspace: production
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      pagerduty_token: ${{ secrets.PAGERDUTY_TOKEN }}

  production_environment_plan_apply:
    name: Production Environment Terraform Plan and Apply
    needs: [
      'production_account_plan_apply',
      'create_tags'
    ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      terraform_path: 'terraform/environment'
      image_tag: main-${{ needs.create_tags.outputs.version_tag }}
      use_ssh_private_key: true
      workspace: production
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  demo_environment_plan_apply:
    name: Demo Environment Terraform Plan and Apply
    needs: [
      'production_environment_plan_apply',
      'create_tags'
    ]
    uses: ./.github/workflows/sub-task-terraform.yml
    with:
      terraform_path: 'terraform/environment'
      image_tag: main-${{ needs.create_tags.outputs.version_tag }}
      use_ssh_private_key: true
      workspace: demo
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  workflow_complete:
    name: Workflow Complete
    needs: ['production_environment_plan_apply', 'demo_environment_plan_apply']
    runs-on: ubuntu-latest
    steps:
      - name: Completion message
        run: echo "Workflow Complete - Released to Live"
