FROM python:3.14-slim
ARG FUNCTION_DIR="/lambdas/image_request_handler"

# Create function directory
RUN mkdir -p ${FUNCTION_DIR}

COPY app ${FUNCTION_DIR}/app
COPY tests ${FUNCTION_DIR}/tests

COPY --from=ghcr.io/astral-sh/uv@sha256:b46b03ddfcfbf8f547af7e9eaefdf8a39c8cebcba7c98858d3162bd28cf536f6 /uv /uvx /bin/
COPY pyproject.toml uv.lock ./
RUN uv export --locked --group dev -o requirements-dev.txt

RUN apt-get update && \
    apt-get upgrade expat -y

# Install the runtime interface client
RUN python -m pip install --upgrade pip
RUN python -m pip install \
        --target ${FUNCTION_DIR} \
        --requirement requirements-dev.txt

ENV PYTHONPATH "${PYTHONPATH}:${FUNCTION_DIR}"
COPY run-tests.sh run-tests.sh
RUN pip3 install coverage==7.2.5 && chmod 755 run-tests.sh
# Set the entrypoint for the unit tests
ENTRYPOINT [ "./run-tests.sh" ]
