FROM python:3.10.9-slim
ARG FUNCTION_DIR="/lambdas/image_request_handler"

# Create function directory
RUN mkdir -p ${FUNCTION_DIR}

COPY app ${FUNCTION_DIR}/app
COPY tests ${FUNCTION_DIR}/tests

COPY requirements.txt requirements.txt
COPY requirements-dev.txt requirements-dev.txt

# Install the runtime interface client
RUN python -m pip install --upgrade pip
RUN python -m pip install \
        --target ${FUNCTION_DIR} \
        --requirement requirements.txt
RUN python -m pip install \
        --target ${FUNCTION_DIR} \
        --requirement requirements-dev.txt

ENV PYTHONPATH "${PYTHONPATH}:${FUNCTION_DIR}"

ENTRYPOINT [ "python", "-m", "pytest", "/lambdas/image_request_handler/tests/" ]
