FROM python:3.11.5-slim
ARG FUNCTION_DIR="/lambdas/image_request_handler"

# Create function directory
RUN mkdir -p ${FUNCTION_DIR}

COPY app ${FUNCTION_DIR}/app
COPY tests ${FUNCTION_DIR}/tests

COPY requirements.txt requirements.txt
COPY requirements-dev.txt requirements-dev.txt

# Install the runtime interface client
RUN python -m pip install --upgrade pip
RUN python -m pip install \
        --target ${FUNCTION_DIR} \
        --requirement requirements.txt
RUN python -m pip install \
        --target ${FUNCTION_DIR} \
        --requirement requirements-dev.txt

ENV PYTHONPATH "${PYTHONPATH}:${FUNCTION_DIR}"
COPY run-tests.sh run-tests.sh
RUN pip3 install coverage==7.2.5 && chmod 755 run-tests.sh
# Set the entrypoint for the unit tests
ENTRYPOINT [ "./run-tests.sh" ]
