[project]
name = "image-request-handler"
version = "0.1.0"
requires-python = ">=3.14,<3.15"
dependencies = [
    "boto3==1.43.50",
    "awslambdaric==3.1.1",
    "setuptools==83.0.0",
    "imageio==2.37.3",
    "aws-xray-sdk==2.15.0",
]

[dependency-groups]
dev = [
    "coverage==7.2.5",
    "moto==5.2.2",
    "pytest==9.1.1",
]

[tool.uv]
package = false
